# Generated by Django 3.0.6 on 2021-03-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpdatabase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydb',
            name='pred',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
